volumes:
  db_data:


services:
  db:
    image: postgres:15.10-alpine@sha256:1fe722aee536e138d4c530d5dfb8055f12adbaefa552a208fe691ce70670546e
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $DB_USER -d $DB_NAME'"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - path: .env
        required: false
      - path: app/.env
        required: false
    environment:
      - POSTGRES_USER=${DB_USER?}
      - POSTGRES_PASSWORD=${DB_PASSWORD?}
      - POSTGRES_DB=${DB_NAME-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web1:
    build: ./app
    restart: always
    environment:
      SERVER_ID: SERVER-1
    env_file:
      - path: .env
        required: false
      - path: app/.env
        required: false
    depends_on:
      db:
        condition: service_healthy

  web2:
    build: ./app
    restart: always
    environment:
      SERVER_ID: SERVER-2
    env_file:
      - path: .env
        required: false
      - path: app/.env
        required: false
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.27.3-alpine@sha256:41523187cf7d7a2f2677a80609d9caa14388bf5c1fbca9c410ba3de602aaaab4
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2

  pgadmin:
    restart: always
    image: dpage/pgadmin4:8.11.0
    depends_on:
      db:
        condition: service_started
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD?}
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80
