name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - master 
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: KhudyakovGleb
          password: ${{secrets.GITHUB_TOKEN}} 

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/Fast_chemistry:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/Fast_chemistry:latest
