name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Poetry setup
        run: |
          pip install poetry==1.8.3
          poetry config virtualenvs.create false
          poetry install --no-root --only main

      - name: Run tests with PyTest
        run: |
          docker compose up db -d
          poetry run pytest
